### ISSUE TITLE
Getting a Nokogiri warning on mac os

### ISSUE THREAD

**Issue by tjaadvd** [quilt/lobsters#4]
Hi,
When running this with Kitematic on mac os, I get the following warning:
'WARNING: Nokogiri was built against LibXML version 2.9.1, but has dynamically loaded 2.8.0'.
I see that is is not an important error, but it makes me unable to run the docker image.
Do you care to help?
Thomas

`WARNING: Nokogiri was built against LibXML version 2.9.1, but has dynamically loaded 2.8.0
DEPRECATION WARNING: Currently, Active Record suppresses errors raised within `after_rollback`/`after_commit` callbacks and only print them to the logs. In the next version, these errors will no longer be suppressed. Instead, the errors will propagate normally just like in other Active Record callbacks.
You can opt into the new behavior and remove this warning by setting:
  config.active_record.raise_in_transactional_callbacks = true
 (called from mon_synchronize at /usr/local/lib/ruby/2.3.0/monitor.rb:214)
rake aborted!
Cannot load `Rails.application.database_configuration`:
Could not load database configuration. No such file - ["config/database.yml"]
/usr/local/bundle/gems/railties-4.2.8/lib/rails/application/configuration.rb:110:in `database_configuration'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/railtie.rb:41:in `block (3 levels) in <class:Railtie>'
Could not load database configuration. No such file - ["config/database.yml"]
/usr/local/bundle/gems/railties-4.2.8/lib/rails/application/configuration.rb:110:in `database_configuration'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/railtie.rb:41:in `block (3 levels) in <class:Railtie>'
Tasks: TOP => db:create => db:load_config
(See full trace by running task with --trace)`

**Comment by kklin** [comment]
Hi Thomas,

This Docker image is actually intended to be used with [Quilt](http://quilt.io).

It looks like to me like the actual reason why the image doesn't run is that the database isn't properly configured. We configure that in the accompanying Quilt spec [here](https://github.com/quilt/lobsters/blob/master/lobsters.js#L21).

Full disclosure, I'm a developer on Quilt, but if you're interested in deploying lobste.rs I'd recommend [setting up Quilt](https://github.com/quilt/quilt/blob/master/docs/GettingStarted.md), starting the Quilt daemon with `quilt daemon`, and then booting lobste.rs with `quilt run lobsters-example.js`! If you do decide to try it out, don't hesitate to ask me for more details about how to get it up and running -- our documentation is kind of scattered 😄

**Comment by tjaadvd** [comment]
Thanks for letting me know, and that's an interesting framework!
